#pragma once
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <string.h> 
#include "carte.h"
#include "matrice.h"
#include "player.h"
#include "liste.h"
#include "jeu.h"
#include "shuffle.h"
#include "affichage.h"
#include "image.h"